#.travis.yml

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: reneval@gmail.com
    on_success: reneval@gmail.com