#.travis.yml
dist: trusty

language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add @angular/cli

install:
  - yarn install
script:
  - ng test --watch false



before_script:
  - npm install -g @angular/cli
  - ng build --prod

script:
  - ng test --watch=false

notifications:
  email:
    on_failure: reneval@gmail.com
    on_success: reneval@gmail.com